// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwQ03ppXALwKKknVCX54cnIXRySBhJ230',
    appId: '1:210897478481:web:e5492a756c670ebd74e970',
    messagingSenderId: '210897478481',
    projectId: 'tienda-emprendimientos',
    authDomain: 'tienda-emprendimientos.firebaseapp.com',
    storageBucket: 'tienda-emprendimientos.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgTdawX7Zue7hbB7BTYUkLiQy7DLMaeJY',
    appId: '1:210897478481:android:506fa6296fdd409574e970',
    messagingSenderId: '210897478481',
    projectId: 'tienda-emprendimientos',
    storageBucket: 'tienda-emprendimientos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsb8j6ieuziQRaE4cHxTjHPWd2pWMXr4E',
    appId: '1:210897478481:ios:cbbf02d488e923ba74e970',
    messagingSenderId: '210897478481',
    projectId: 'tienda-emprendimientos',
    storageBucket: 'tienda-emprendimientos.firebasestorage.app',
    iosBundleId: 'com.example.pryTiendaProductosLocales',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsb8j6ieuziQRaE4cHxTjHPWd2pWMXr4E',
    appId: '1:210897478481:ios:cbbf02d488e923ba74e970',
    messagingSenderId: '210897478481',
    projectId: 'tienda-emprendimientos',
    storageBucket: 'tienda-emprendimientos.firebasestorage.app',
    iosBundleId: 'com.example.pryTiendaProductosLocales',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwQ03ppXALwKKknVCX54cnIXRySBhJ230',
    appId: '1:210897478481:web:67a6aade1fa94ecd74e970',
    messagingSenderId: '210897478481',
    projectId: 'tienda-emprendimientos',
    authDomain: 'tienda-emprendimientos.firebaseapp.com',
    storageBucket: 'tienda-emprendimientos.firebasestorage.app',
  );
}
